### ISSUE TITLE
Syntax error reported when communicating with mobile terminal

### ISSUE THREAD

**Issue by boge158** [openxrlab/xrlocalization#25]
Print：
Begin loc
Load done
dict_keys(['image', 'intrinsic'])
[09/08/2023 15:34:22 INFO] Local feature number: 1996
[09/08/2023 15:34:23 INFO] Coarse location number: 3
[09/08/2023 15:34:23 INFO] 3d points size: 4686
[09/08/2023 15:34:23 INFO] k:3, ratio:0.7, thres:0.9
[09/08/2023 15:34:23 INFO] Knn ratio match size: 1616
[09/08/2023 15:34:23 INFO] Match number: 677
[09/08/2023 15:34:23 INFO] Inlier number: 10
[09/08/2023 15:34:23 INFO] 3d points size: 2990
[09/08/2023 15:34:23 INFO] k:3, ratio:0.7, thres:0.9
[09/08/2023 15:34:23 INFO] Knn ratio match size: 1764
[09/08/2023 15:34:23 INFO] Match number: 687
[09/08/2023 15:34:23 INFO] Inlier number: 18
[09/08/2023 15:34:23 ERROR] Exception on /loc [POST]
Traceback (most recent call last):
  File "/home/zjlab/anaconda3/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/zjlab/anaconda3/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/zjlab/anaconda3/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/zjlab/anaconda3/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/zjlab/anaconda3/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/zjlab/anaconda3/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "run_web_server.py", line 63, in loc
    if output['ninlier'] > 0:
NameError: name 'output' is not defined
[09/08/2023 15:34:23 INFO] **.**.**.*** - - [08/Sep/2023 15:34:23] "POST /loc HTTP/1.1" 500 -

How can I solve it？

**Comment by HailinYu0414** [comment]
Please replace line 58 in file 'run_web_server.py' with `output = loc_server.refine_localize(image, camera, ref_image_ids)`.
