### ISSUE TITLE
在生成features.bin时出现 IndexError: index 2501 is out of bounds for axis 1 with size 2484 错误

### ISSUE THREAD

**Issue by liuPseu** [openxrlab/xrlocalization#28]
非常感谢你的工作
但是我用你的程序在跑自己数据集的时候出现了问题
在生成features.bin时出现 IndexError: index 2501 is out of bounds for axis 1 with size 2484 
我先是用COLMap生成了images.bin，point3Ds.bin和cameras.bin
 **0.** Extract local feature
python3 tools/recon_feature_extract.py \
       --image_dir /path/to/images \
       --image_bin_path /path/to/model/images.bin \
       --feature_bin_path /path/to/features.bin \
       --extractor d2net
用上述的程序生成了features.bin

**1.** Perform 2D-2D feature matching
```commandline
python3 tools/recon_feature_extract.py \
       --recon_path /path/to/model \
       --feature_bin_path /path/to/features.bin \
       --match_bin_path /path/to/matches.bin
这个程序我没有运行起来，而且我看了程序，发现没有--recon_path这个参数

接着，我用上述生成的features.bin运行下面的程序，
xrloc:
```commandline
python3 tools/loc_convert_reconstruction.py \
    --feature_path /path/to/features.bin \
    --model_path /path/to/include/images.bin/and/points3Ds.bin/directory \
    --output_path /path/to/map/directory

Traceback (most recent call last):
  File "tools/loc_convert_reconstruction.py", line 140, in <module>
    main(args.feature_path, args.model_path, args.output_path)
  File "tools/loc_convert_reconstruction.py", line 130, in main
    crm.convert_to_mean_descriptor_map(output_path)
  File "tools/loc_convert_reconstruction.py", line 115, in convert_to_mean_descriptor_map
    self.compute_mean_descriptor()
  File "tools/loc_convert_reconstruction.py", line 94, in compute_mean_descriptor
    descriptor = self.features[image_id].descriptors[:, point2d_id]
IndexError: index 2501 is out of bounds for axis 1 with size 2484
出现了上述的报错，我不明白这个错误的来源是什么，是哪一步出现了问题
万分期待您的指导

**Comment by liuPseu** [comment]
这个images.bin里面保存的point2D是由COLMAP提取的特征点，而features.bin是由程序通过D2Net提取的特征点，我看了这两个文件的内容，里面的特征点的位置本来就是对不上的，我不清楚是不是这个问题导致的，急需请教，谢谢。

**Comment by ChEnYoNgB** [comment]
你好请问你是怎么解决的，COLMAP提取的特征点和D2Net提取的特征点对应不上
