### ISSUE TITLE
初学者问题，在运行run_benchmark.py时报错

### ISSUE THREAD

**Issue by gwgc** [openxrlab/xrlocalization#30]
运行run_benchmark.py时报错：提示No module named 'lib.model_test'
请问这是哪个库没有安装吗？在网上没有查到对应的库。谢谢！

(base) root@xr-Virtual-Machine:~/miniconda3/condabin/xrlocalization# python3 run_benchmark.py --map_path /root/xrloc-test-meta/map --query_path /root/xrloc-test-meta/query.txt
[01/14/2024 20:22:26 INFO] Dataset size: 3
[01/14/2024 20:22:26 INFO] ==================================================
[01/14/2024 20:22:26 INFO] ***************** XRLocalization *****************
[01/14/2024 20:22:26 INFO] ==================================================
Traceback (most recent call last):
  File "run_benchmark.py", line 52, in <module>
    main(args.query_path, args.map_path, args.json)
  File "run_benchmark.py", line 20, in main
    loc = Localizer(map_path)
  File "/root/miniconda3/condabin/xrlocalization/xrloc/localizer.py", line 57, in __init__
    self.lextractor = Extractor(self.config['local_feature'])
  File "/root/miniconda3/condabin/xrlocalization/xrloc/features/extractor.py", line 38, in __init__
    model = self.make_model(name)
  File "/root/miniconda3/condabin/xrlocalization/xrloc/features/extractor.py", line 106, in make_model
    module = __import__(module_path, fromlist=[''])
  File "/root/miniconda3/condabin/xrlocalization/xrloc/features/d2net.py", line 10, in <module>
    from lib.model_test import D2Net as D2N
ModuleNotFoundError: No module named 'lib.model_test'

**Comment by HailinYu0414** [comment]
You did not pull the 3rdparty dependencies. Try cd xrlocalization & git submodule update --init --recursive

**Comment by gwgc** [comment]
感谢您的回复，重新安装了乌班图系统，已经可以运行run_benchmark.py了。但是在学习下一步又出现了新问题，在Benchmark Evaluation章节，“0. Generate localization map“生成本地化地图，参考Generate localization map章节中。先要通过xrloc生成Re-triangulation吗？
在“Re-triangulation by [xrloc]”的链接中要对自己拍摄的图片进行处理吗？原文中的这段话如何理解，准备自己的图片，cameras.bin、images.bin、points3D.bin这几个文件是通过图片生成的吗。
Assume we have reference images and the sparse model that is COLMAP format:
+---images/
|    |-- ...
+---model/
     |--cameras.bin
     |--images.bin
     |--points3D.bin

**Comment by HailinYu0414** [comment]
Re-triangulation那一步要使用xrloc和xrsfm配合完成。具体流程是先使用xrloc对参考图像使用指定特征进行特征抽取、特征匹配，然后再运行xrsfm中的三角化工具。
